config/routes.rb
Rails.application.routes.draw do
  match "/signout" => "sessions#destroy", via: [ :get, :post ]
  match "/adauth" => "sessions#create" , via: [ :get, :post ]
  resources :sessions
  get 'welcome/index'

post 'assets/:id/activate'  => "assets#activate", as: 'activate_asset'
post 'assets/:id/deactivate'  => "assets#deactivate", as: 'deactivate_asset'

post 'users/:id/activate'  => "users#activate", as: 'activate_user'
post 'users/:id/deactivate'  => "users#deactivate", as: 'deactivate_user'

get 'reservations/reports' => "reservations#reports", as: 'report_reservations'
post 'reservations/report' => "reservations#report", as: 'export_reservation'

   root 'reservations#new'

	resources :users 
	resources :reservations 
	resources :assets

end

app/models/user.rb
class User < ActiveRecord::Base
include Adauth::Rails::ModelBridge

AdauthMappings = {
	:login => :login,
	:group_strings => :cn_groups

	}

AdauthSearchField = [ :login, :login ]

#validates :first_name, :last_name, :login, :email, :active, presence: true
validates :first_name, :last_name, :login, :email,  presence: true
has_many :reservations, inverse_of: :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
        def show
                @user=User.find(params[:id])
        end
        def index
                @users=User.all
        end
        def create
#                @user=User.new(user_params)
#                @user.save
                @user=User.create_from_adauth(adauth_model) 
                redirect_to @user
        end
        def new
#                @user= User.new
                @user=User.create_from_adauth(adauth_model) 
        end
        def edit
                @user=User.find(params[:id])
        end
        def update
                @user=User.find(params[:id])
                if @user.update(user_params)
                        redirect_to @user
                else
                        render edit
                end
        end
        def destroy
                @user=User.find(params[:id])
                @user.destroy
                redirect_to users_path
        end
 	def deactivate
                @user=User.find(params[:id])
                @user.update(active: 'N')
                redirect_to users_path
        end
        def activate
                @user=User.find(params[:id])
                @user.update(active: 'Y')
                redirect_to users_path
        end

       private
       def user_params
       params.require(:user).permit(:first_name,:last_name,:login, :email, :active)
       end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div id="user_list">
<%= form_for @user, url: {action: "update"} do |f| %>
        <%= f.label :first_name %>
        <%= text_field :user, :first_name %>
        <%= f.label :last_name %>
        <%= text_field :user, :last_name %>
        <%= f.label :login %>
        <%= text_field :user, :login%>
        <%= f.label :email%>
        <%= text_field :user, :email%>
        <%= f.label :active%>
        <%= f.check_box :active, {}, "Y", "N"%>
        <%= f.submit "Update" %>
<% end %>
</div>

app/views/users/index.html.erb
<table id="user_list">
<tr>
<th>Username</th>
<th>First Name</th>
<th>Last Name</th>
<th>Email Address</th>
<th>Active?</th>
</tr>
<% @users.each do |user| %>
<tr>
<td><%= user.login%></td>
<td><%= user.first_name %></td>
<td><%= user.last_name %></td>
<td><%= user.email %></td>
<td><%= user.active %></td>
<td class="edit list_button"><%= link_to "Edit", edit_user_path(user) %></td>
<td class="activate list_button"><%= link_to "Activate", activate_user_path(user), action: "activate", data: {confirm: "Are you sure?" }, method: :post %></td>
<td class="deactivate list_button"><%= link_to "Deactivate", deactivate_user_path(user), action: "deactivate", data: {confirm: "Are you sure?" }, method: :post %></td>
<td class="remove list_button"><%= link_to "Remove", user, method: :delete, data: {confirm: "Are you sure?" } %></td>
</tr>
<% end %>
</table>

app/views/users/show.html.erb
<table id="user_list">
<tr>
<th>Username</th>
<th>First Name</th>
<th>Last Name</th>
<th>Email Address</th>
<th>Active?</th>
</tr>
<tr>
<td><%= @user.login%></td>
<td><%= @user.first_name %></td>
<td><%= @user.last_name %></td>
<td><%= @user.email %></td>
<td><%= @user.active %></td>
<td><%= link_to "Edit", edit_user_path(@user) %></td>
<td><%= link_to "Remove", @user, method: :delete, data: {confirm: "Are you sure?" } %></td>
</tr>
</table>