config/routes.rb
Rails.application.routes.draw do
  match "/signout" => "sessions#destroy", via: [ :get, :post ]
  match "/adauth" => "sessions#create" , via: [ :get, :post ]
  resources :sessions
  get 'welcome/index'

post 'assets/:id/activate'  => "assets#activate", as: 'activate_asset'
post 'assets/:id/deactivate'  => "assets#deactivate", as: 'deactivate_asset'

post 'users/:id/activate'  => "users#activate", as: 'activate_user'
post 'users/:id/deactivate'  => "users#deactivate", as: 'deactivate_user'

get 'reservations/reports' => "reservations#reports", as: 'report_reservations'
post 'reservations/report' => "reservations#report", as: 'export_reservation'

   root 'reservations#new'

	resources :users 
	resources :reservations 
	resources :assets

end

app/views/shared/_error.html.erb
<div id="error_explaination">
<h2><%= pluralize(object.errors.count, "error") %>
found.</h2>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li> <%= msg %> </li>
<% end %>
</ul>
</div>

app/views/shared/_header.html.erb
<div id="header">EMC Scheduler - Philly Office
<span id="menu_links" >
<%= link_to image_tag("blue-button-planner.png",  {class: "header_button", alt: "New Reservation"}) + "New", new_reservation_path, method: :get %>
<%= link_to image_tag("blue-button-doc-checks.png",{class: "header_button", alt: "My Reservations"}) + "Mine", reservations_path(:mine=>"Y"), method: :get %>
<%= link_to image_tag("blue-button-document.png",  {class: "header_button", alt: "All Reservations"}) + "All", reservations_path, method: :get %>
<% if current_user and current_user.admin == 'Y' %>
        <%= link_to image_tag("blue_button-2-people.png",  {class: "header_button", alt: "All Reservations"}) + "Users", users_path %>
        <%= link_to image_tag("blue_button-gears.png",  {class: "header_button", alt: "All Reservations"}) + "Assets",assets_path %>
	<%= link_to image_tag("blue_button-comp-meter.png",  {class: "header_button", alt: "All Reservations"}) + "Reports", report_reservations_path %>
<% end %>
<%= link_to image_tag("blue_button-migrate.png",  {class: "header_button", alt: "All Reservations"}) + "Logout", signout_path, method: :get %>
</span>
</div>

app/views/shared/_ip_list.html.erb
<div id="ip_list">
<h4>View IP Addresses</h4>
<table>
<tr>
<th>Site</th>
<th>Equipment</th>
<th>IP Address</th>
</tr>
<% @ip_list.each do |a| %>
        <tr>
                <td><%=a.site%></td>
                <td><%=a.name%></td>
                <td><%=a.ip_address%></td>
        </tr>
<% end %>
</table>
</div>