config/routes.rb
Rails.application.routes.draw do
  match "/signout" => "sessions#destroy", via: [ :get, :post ]
  match "/adauth" => "sessions#create" , via: [ :get, :post ]
  resources :sessions
  get 'welcome/index'

post 'assets/:id/activate'  => "assets#activate", as: 'activate_asset'
post 'assets/:id/deactivate'  => "assets#deactivate", as: 'deactivate_asset'

post 'users/:id/activate'  => "users#activate", as: 'activate_user'
post 'users/:id/deactivate'  => "users#deactivate", as: 'deactivate_user'

get 'reservations/reports' => "reservations#reports", as: 'report_reservations'
post 'reservations/report' => "reservations#report", as: 'export_reservation'

   root 'reservations#new'

	resources :users 
	resources :reservations 
	resources :assets

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	validates :reservation_type, :start_date, :start_time, :end_time, :quarter, :year, :active, presence: true
	has_and_belongs_to_many :assets, inverse_of: :reservation
	accepts_nested_attributes_for :assets, allow_destroy: true
	belongs_to :user , inverse_of: :reservations

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |product|
				csv << reservation.attributes.values_at(*column_names)
      			end
    		end
  	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	def show
                @reservation=Reservation.find(params[:id])
		@user_full_name=User.find(@reservation.user_id).first_name + " " + User.find(@reservation.user_id).last_name
        end

	def reports
		render "reports"
	end

	def report
		@year=params[:year]
		@quarter=params[:quarter]
		@reservations=Reservation.joins(:user).where("quarter = ? and year = ?", @quarter, @year).order(:start_date).order(:start_time).select(:start_date, :start_time, 
								:end_time, :reservation_type, :partner, :customer, :quarter, :year, :user_id, "users.login" )
		@userReservationsCount=Reservation.joins(:user).where("quarter = ? and year = ?", @quarter, @year).group("users.login").count
		@typeCount=Reservation.where("quarter = ? and year = ?", @quarter, @year).group(:reservation_type).count

		@filename="Scheduler Report-" + @year + "Q" +@quarter + ".xls"
		headers["Content-Disposition"] = "attachment; filename=\"#{@filename}\"" 		
		respond_to do |format|
			format.xls 
		end 
	end
        def index
		if ( params[:mine] == "Y" ) 
			@reservations=Reservation.where(:user_id => current_user.id).order(start_date: :desc).order(start_time: :desc)
		else
                	@reservations=Reservation.order(start_date: :desc).order(start_time: :desc)
		end
        end

        def create
                @reservation=Reservation.new(reservation_params)
		@all_assets=Asset.where(active: "Y").order(:name)
		@all_sites= Asset.select(:site).order(:site).distinct
		@ip_list=Asset.where(active: "Y").order(:site).order(:name).select(:site,:name, :ip_address)


		if (@reservation.start_date.nil?) 
			@reservation.errors.add(:start_date, " cannot be blank.")
		end

		if (@reservation.start_time.nil?) 
			@reservation.errors.add(:start_time, " cannot be blank.")
		end
		if (@reservation.end_time.nil?) 
			@reservation.errors.add(:end_time, " cannot be blank.")
		end

		if (@reservation.errors.blank? and @reservation.start_time >= @reservation.end_time)
			@reservation.errors.add(:start_time, "must preceed End time.")
		end
		unless (@reservation.assets.any?)
			@reservation.errors.add(:base, "Please select at least one asset to reserve.")
		end

		@start_time=@reservation.start_time.strftime("%H:%M:%S")
		@end_time=@reservation.end_time.strftime("%H:%M:%S")

		unless (@reservation.errors.blank? and all_assets_available?(@reservation,@start_time, @end_time))
			@reservation.assets.each do |a|
			if(Asset.joins(:reservations).exists?(["reservations.start_date= ? and assets.id = ? and ((? between reservations.start_time and reservations.end_time) or (? between reservations.start_time and reservations.end_time)  or (reservations.start_time between ? and ? ) or (reservations.end_time between ? and ? ))",
						 @reservation.start_date,a.id, @start_time, @end_time, @start_time,  @end_time,@start_time, @end_time]))
					@reservation.errors.add(:base, Asset.find(a.id).name + " is not available at this time.")
				end
			end
		end


		if (@reservation.errors.any?)
			@all_sites= Asset.select(:site).distinct
			@all_assets= Asset.where("active='Y'")
			render action: :new
		else
			@reservation.user_id=current_user.id
			@reservation.year=@reservation.start_date.year
			@reservation.quarter=get_quarter(@reservation.start_date.month)
			@reservation.active="Y"
                	if (@reservation.save )
                		redirect_to @reservation
			else
				redirect_to action: :new
			end
		end
        end
        def new
                @reservation= Reservation.new
		@all_assets=Asset.where(active: "Y").order(:name)
		@all_sites= Asset.select(:site).order(:site).distinct
		@ip_list=Asset.where(active: "Y").order(:site).order(:name).select(:site,:name, :ip_address)
        end
        def edit
                @reservation=Reservation.find(params[:id])
		@all_assets=Asset.where(active: "Y").order(:name)
		@all_sites= Asset.select(:site).order(:name).distinct
        end

        def update
                @reservation=Reservation.find(params[:id])
		if @reservation.assets.blank?
			@reservation.errors.add(:base, "Please select at least one asset to reserve.")
		end
                if @reservation.errors.blank? and @reservation.update(reservation_params)
                        redirect_to @reservation
                else
                        render edit
                end
        end
        def destroy
                @reservation=Reservation.find(params[:id])
                @reservation.destroy
                redirect_to reservations_path
        end

	private
	def reservation_params
		params.require(:reservation).permit(:start_date, :start_time, :end_time, :reservation_type, :partner, :customer, {:asset_ids => []})
	end

	def get_quarter(the_month)
		if (the_month >= 10) 
			quarter=4
		elsif (the_month >=7)
			quarter=3
		elsif (the_month >=4)
			quarter=2
		elsif (the_month >=1)
			quarter=1	
		end
		return  quarter
	end
	
	def all_assets_available?(reservation, start_time, end_time) 
		result=true
		reservation.assets.each do |a|
			if(Asset.joins(:reservations).exists?(["reservations.start_date= ? and assets.id = ? and ((? between reservations.start_time and reservations.end_time) or (? between reservations.start_time and reservations.end_time) or (reservations.start_time between ? and ? ) or (reservations.end_time between ? and ? ))",
						 reservation.start_date, a.id, start_time, end_time, start_time,  end_time,start_time, end_time]))
				result=false
				break
			end
		end
		return result
	end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/edit.html.erb
<% if @reservation.errors.any? %>
<%= render partial: "shared/error", locals: { object: @reservation} %>
<% end %>

<%= form_for @reservation, url: {action: "update"}, html: {method: "patch"} do |f| %>
	<div id="reservation_form">
	<div id="reservation_header" class="form_header">Reserve</div>
	<table id="reservation_select">
	<tr>
	<td> <%= f.label :reservation_type %> </td>
	<td><%= select(:reservation, :reservation_type, options_for_select([['Demo','Demo'],['Partner Training','Partner Training'], 
				['Internal Training','Internal Training'],['Maintenance/Upgrades','Maintenance/Upgrades'],['POC','POC']],"Demo")) %>  <td/>
	</tr>
	<tr>
  	<td><%= f.label :start_date %></td>
  	<td><%= text_field :reservation, :start_date %> </td>
	</tr>
	<tr>
  	<td><%= f.label :start_time %></td>
  	<td><%= text_field :reservation, :start_time, :value => @reservation.start_time.strftime("%I:%M %P") %> </td>
	</tr>
	<tr>
  	<td><%= f.label :end_time %></td>
  	<td><%= text_field :reservation, :end_time, :value  => @reservation.end_time.strftime("%I:%M %P")%> </td>
	</tr>
	<tr>
  	<td><%= f.label :partner %></td>
  	<td><%= f.text_field :partner %> </td>
	</tr>
	<tr>
  	<td><%= f.label :customer %> </td>
  	<td><%= f.text_field :customer %> </td>
	</tr>
	</table>
	</div>
	<div id="asset_form">
	<div id="asset_header" class="form_header">Equipment</div>
	<div id="asset_select">
	<% @all_sites.each do |a| %>
		<div id="<%=a.site%>" class="asset_site"><%=a.site%>
		<% @all_assets.where(site: a.site).each do |a|%>
			<%= fields_for :assets do |asset_form| %>
				<% if (@reservation.assets.exists?(a.id)) %>
					<% @checked=true %>
				<% else %>
					<% @checked=false %>
				<% end %>
				<div class="asset_item"><%= check_box_tag "reservation[asset_ids][]", a.id, @checked%>
				<%= asset_form.label nil, a.name %> </div>
			<% end %>
		<% end %>
		</div>
	<% end %>
	</div>
	</div>
	<div id="clearing"></div>
	<div id="reserve_button"><%= f.submit "Reserve", class: "big_button" %></div>
<% end %>

app/views/reservations/index.html.erb
<div id="reservation_list">
<% @reservations.each do |reservation| %>
	<div class="reservation">
		<table>
		<tr>
		<th>Reservation Date</th>
		<th>Start</th>
		<th>End</th>
		<th>Type</th>
		<th>User</th>
		<th>Partner</th>
		<th>Customer</th>
		</tr>
		<tr>
		<td><%= reservation.start_date.strftime("%D") %></td>
		<td><%= reservation.start_time.strftime("%I:%M %P") %> </td>
		<td><%= reservation.end_time.strftime("%I:%M %P")  %> </td>
		<td><%= reservation.reservation_type %></td>
		<td><%= User.find(reservation.user_id).first_name %> <%= User.find(reservation.user_id).last_name %></td>
		<td><%= reservation.partner %></td>
		<td><%= reservation.customer %></td>
		<% if current_user.id == reservation.user_id %>
			<td class="edit list_button"><%= link_to "Edit", edit_reservation_path(reservation), method: :get %></td>
			<td class="remove list_button"><%= link_to "Remove", reservation, method: :delete, data: {confirm: "Are you sure?" } %></td>
		<% end %>
		</tr>
		</table>
		<div class="reservation_assets">
	       		<h4>View Equipment</h4>
	       		<div>
	               		<% reservation.asset_ids.each do |i| %>
					<%= Asset.find(i).name %><br/>
	               		<% end %>
	       		</div>
		</div>
	</div>
<% end %>
</div>

app/views/reservations/new.html.erb
<% if @reservation.errors.any? %>
<%= render partial: "shared/error", locals: { object: @reservation} %>
<% end %>

<%= render "shared/ip_list" %>
<%= form_for @reservation, url: {action: "create"} do |f| %>
	<div id="reservation_form">
	<div id="reservation_header" class="form_header">Reserve</div>
	<table id="reservation_select">
	<tr>
	<td> <%= f.label :reservation_type %> </td>
	<td><%= select(:reservation, :reservation_type, options_for_select([['Demo','Demo'],['Partner Training','Partner Training'], 
				['Internal Training','Internal Training'],['Maintenance/Upgrades','Maintenance/Upgrades'],['POC','POC']],"Demo")) %>  <td/>
	</tr>
	<tr>
  	<td><%= f.label :start_date %></td>
  	<td><%= text_field :reservation, :start_date %> </td>
	</tr>
	<tr>
  	<td><%= f.label :start_time %></td>
  	<td><%= text_field :reservation, :start_time %> </td>
	</tr>
	<tr>
  	<td><%= f.label :end_time %></td>
  	<td><%= text_field :reservation, :end_time %> </td>
	</tr>
	<tr>
  	<td><%= f.label :partner %></td>
  	<td><%= f.text_field :partner %> </td>
	</tr>
	<tr>
  	<td><%= f.label :customer %> </td>
  	<td><%= f.text_field :customer %> </td>
	</tr>
	</table>
	</div>
	<div id="asset_form">
	<div id="asset_header" class="form_header">Equipment</div>
	<div id="asset_select">
	 <% @all_sites.each do |a| %>
		<div id="<%=a.site%>" class="asset_site"><%=a.site%>
                <% @all_assets.where(site: a.site).each do |a|%>
			<%= fields_for :assets do |asset_form| %>
				<div class="asset_item"><%= check_box_tag "reservation[asset_ids][]", a.id %>
				<%= asset_form.label nil, a.name %> </div>
			<% end %>
		<% end %>
		</div>
	<% end %>
	</div>
	</div>
	<div id="clearing"></div>
	<div id="reserve_button"><%= f.submit "Reserve", class: "big_button" %></div>
<% end %>

app/views/reservations/report.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="<%= "Q" + @quarter + "-" + @year %>">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Date</Data></Cell>
        <Cell><Data ss:Type="String">Start Time</Data></Cell>
        <Cell><Data ss:Type="String">End Time</Data></Cell>
        <Cell><Data ss:Type="String">Type</Data></Cell>
        <Cell><Data ss:Type="String">Partner</Data></Cell>
        <Cell><Data ss:Type="String">Customer</Data></Cell>
        <Cell><Data ss:Type="String">User</Data></Cell>
      </Row>
    <% @reservations.each do |reservation| %>
      <Row>
        <Cell><Data ss:Type="String"><%= reservation.start_date.strftime("%m/%d/%Y") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reservation.start_time.strftime("%I:%M %P") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reservation.end_time.strftime("%I:%M %P") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reservation.reservation_type %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reservation.partner %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reservation.customer %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reservation.user.login %></Data></Cell>
      </Row>
    <% end %>
	<Row></Row>
	<Row></Row>
	<Row></Row>
	<Row></Row>
	<Row></Row>
      <Row>
        <Cell><Data ss:Type="String">User</Data></Cell>
        <Cell><Data ss:Type="String"># of Events</Data></Cell>
      </Row>
    <% @userReservationsCount.each do |user| %>
      <Row>
        <Cell><Data ss:Type="String"><%= user[0] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user[1]%></Data></Cell>
      </Row>
    <% end %>
	<Row></Row>
	<Row></Row>
	<Row></Row>
	<Row></Row>
	<Row></Row>
      <Row>
        <Cell><Data ss:Type="String">Reservation Type</Data></Cell>
        <Cell><Data ss:Type="String"># of Events</Data></Cell>
      </Row>
    <% @typeCount.each do |type| %>
      <Row>
        <Cell><Data ss:Type="String"><%= type[0] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= type[1]%></Data></Cell>
      </Row>
    <% end %>
    </Table>

  </Worksheet>
</Workbook>

app/views/reservations/reports.html.erb
<div id="report_form">
<div id="report_header" class="form_header">Report</div>
<%=form_tag("/reservations/report.xls", method: "post") do %>
	<%= label_tag(:quarter, "Quarter") %>
        <%= select_tag(:quarter, options_for_select([['Q1','1'],['Q2','2'], ['Q3','3'],['Q4','4']],"Q1")) %>
	<%= label_tag(:year, "year") %>
	<%= text_field_tag(:year, Time.now.strftime("%Y")) %>
  	<%= submit_tag "Generate Report" %>
<% end %>
</div>

app/views/reservations/show.html.erb
<% if @reservation.errors.any? %>
<%= render partial: "shared/error", locals: { object: @reservation} %>
<% end %>

<div id="reservation_list">
	<table>
	<tr>
	<th>Reservation Date</th>
	<th>Start</th>
	<th>End</th>
	<th>Type</th>
	<th>User</th>
	<th>Partner</th>
	<th>Customer</th>
	</tr>
	<tr>
	<td><%= @reservation.start_date.strftime("%D") %></td>
	<td><%= @reservation.start_time.strftime("%I:%M %P") %> </td>
	<td><%= @reservation.end_time.strftime("%I:%M %P")  %> </td>
	<td><%= @reservation.reservation_type %></td>
	<td><%= @user_full_name %></td>
	<td><%= @reservation.partner %></td>
	<td><%= @reservation.customer %></td>
	<% if current_user.id == @reservation.user_id %>
		<td class="edit list_button"><%= link_to "Edit", edit_reservation_path(@reservation), method: :get %></td>
		<td class="remove list_button"><%= link_to "Remove", @reservation, method: :delete, data: {confirm: "Are you sure?" } %></td>
	<% end %>
	</tr>
	</table>
	<div class="reservation_assets">
       		<h4>View Equipment</h4>
       		<div>
               		<% @reservation.asset_ids.each do |i| %>
				<%= Asset.find(i).name %><br/>
               		<% end %>
       		</div>
	</div>
</div>