config/routes.rb
Rails.application.routes.draw do
  match "/signout" => "sessions#destroy", via: [ :get, :post ]
  match "/adauth" => "sessions#create" , via: [ :get, :post ]
  resources :sessions
  get 'welcome/index'

post 'assets/:id/activate'  => "assets#activate", as: 'activate_asset'
post 'assets/:id/deactivate'  => "assets#deactivate", as: 'deactivate_asset'

post 'users/:id/activate'  => "users#activate", as: 'activate_user'
post 'users/:id/deactivate'  => "users#deactivate", as: 'deactivate_user'

get 'reservations/reports' => "reservations#reports", as: 'report_reservations'
post 'reservations/report' => "reservations#report", as: 'export_reservation'

   root 'reservations#new'

	resources :users 
	resources :reservations 
	resources :assets

end

app/models/asset.rb
class Asset < ActiveRecord::Base
validates :name, :ip_address, :test_ping, :site, :active, presence: true
has_and_belongs_to_many :reservations, inverse_of: :asset
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
	def show
                @asset=Asset.find(params[:id])
        end
        def index
                @assets=Asset.all.order(:site).order(:name)
        end
        def create
                @asset=Asset.new(asset_params)
                @asset.save
                redirect_to @asset
        end
        def new
                @asset= Asset.new
        end
        def edit
                @asset=Asset.find(params[:id])
        end
        def update
                @asset=Asset.find(params[:id])
                if @asset.update(asset_params)
                        redirect_to @asset
                else
                        render edit
                end
        end
        def destroy
                @asset=Asset.find(params[:id])
                @asset.destroy
                redirect_to assets_path
        end
	def deactivate
		@asset=Asset.find(params[:id])
		@asset.update(active: 'N')
		redirect_to assets_path
	end
	def activate
		@asset=Asset.find(params[:id])
		@asset.update(active: 'Y')
		redirect_to assets_path
	end
	
       private
       def asset_params
       params.require(:asset).permit(:name,:ip_address,:site,:test_ping)
       end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/index.html.erb
<table id="asset_list">
<tr>
<th>Name</th>
<th>Site</th>
<th>IP Address</th>
<th>Ping Test?</th>
<th>Active?</th>
</tr>
<% @assets.each do |asset| %>
<tr>
<td><%= asset.name %></td>
<td><%= asset.site %></td>
<td><%= asset.ip_address %></td>
<td><%= asset.test_ping %></td>
<td><%= asset.active %></td>
<td class="edit list_button"><%= link_to "Edit", edit_asset_path(asset) %></td>
<td class="activate list_button"><%= link_to "Activate", activate_asset_path(asset), data: {confirm: "Are you sure?" }, method: :post %></td>
<td class="deactivate list_button"><%= link_to "Deactivate", deactivate_asset_path(asset), data: {confirm: "Are you sure?", method: :post } %></td>
<td class="remove list_button"><%= link_to "Remove", asset, method: :delete, data: {confirm: "Are you sure?" } %></td>
</tr>
<% end %>
</table>

app/views/assets/show.html.erb
<table>
<tr>
<th>Name</th>
<th>IP Address</th>
<th>Ping Test?</th>
<th>Active?</th>
</tr>
<tr>
<td><%= @asset.name %></td>
<td><%= @asset.ip_address %></td>
<td><%= @asset.test_ping %></td>
<td><%= @asset.active %></td>
<td class="edit list_button"><%= link_to "Edit", edit_asset_path(asset) %></td>
<td class="activate list_button"><%= link_to "Activate", activate_asset_path(asset), data: {confirm: "Are you sure?" }, method: :post %></td>
<td class="deactivate list_button"><%= link_to "Deactivate", deactivate_asset_path(asset), data: {confirm: "Are you sure?", method: :post } %></td>
<td class="remove list_button"><%= link_to "Remove", asset, method: :delete, data: {confirm: "Are you sure?" } %></td>
</tr>
</table>